// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ86cMcvTdiMvTCQP4YtXhF-MJ8XuIfXc',
    appId: '1:990291981224:web:3520d78cef68c48c82239d',
    messagingSenderId: '990291981224',
    projectId: 'device-streaming-6be740f1',
    authDomain: 'device-streaming-6be740f1.firebaseapp.com',
    storageBucket: 'device-streaming-6be740f1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApp46KXXrG7y9kE8_GypwsO0hYqfA8Aac',
    appId: '1:990291981224:android:35f0256bb599c83c82239d',
    messagingSenderId: '990291981224',
    projectId: 'device-streaming-6be740f1',
    storageBucket: 'device-streaming-6be740f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN-E8yMq--rECz2c3SnzCiYSyTtF-5kew',
    appId: '1:990291981224:ios:66b0aa8953b1717882239d',
    messagingSenderId: '990291981224',
    projectId: 'device-streaming-6be740f1',
    storageBucket: 'device-streaming-6be740f1.firebasestorage.app',
    iosBundleId: 'com.example.learningdart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN-E8yMq--rECz2c3SnzCiYSyTtF-5kew',
    appId: '1:990291981224:ios:66b0aa8953b1717882239d',
    messagingSenderId: '990291981224',
    projectId: 'device-streaming-6be740f1',
    storageBucket: 'device-streaming-6be740f1.firebasestorage.app',
    iosBundleId: 'com.example.learningdart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ86cMcvTdiMvTCQP4YtXhF-MJ8XuIfXc',
    appId: '1:990291981224:web:feebaafc0bbddee582239d',
    messagingSenderId: '990291981224',
    projectId: 'device-streaming-6be740f1',
    authDomain: 'device-streaming-6be740f1.firebaseapp.com',
    storageBucket: 'device-streaming-6be740f1.firebasestorage.app',
  );
}
